version: '3.8'

services:
  app:
    build: .
    command: sh -c "uvicorn app.main:app --host=0.0.0.0 --port=8000 --reload"
    container_name: fido-transactions-api
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - /tmp/mongo:/data/db
    ports:
      - 27017:27017