version: '3.8'
services:
  # Application service
  web:
    build: .
    command: sh -c "uvicorn app.main:app --host=0.0.0.0 --port=8000 --reload"
    container_name: fido-transactions-api
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - mongodb
    restart: always
    networks:
      - app-network

  # MongoDB Database
  mongodb:
    image: mongo:8.0.0
    container_name: fido-transactions-db
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
